/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exercicio02Pack;

/**
 *
 * @author aline
 */
public class UIExercicio02 extends javax.swing.JFrame {

    /**
     * Creates new form UIExercicio02
     */
    public UIExercicio02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InputPanel = new javax.swing.JPanel();
        Welcome = new javax.swing.JLabel();
        Lbweight = new javax.swing.JLabel();
        Lbheight = new javax.swing.JLabel();
        Txweight = new javax.swing.JTextField();
        Txheight = new javax.swing.JTextField();
        Btcalc = new javax.swing.JButton();
        OutPanel = new javax.swing.JPanel();
        Lbresp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InputPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Welcome.setText("Bem vindo, informe os dados abaixo para conhecer sua dieta ideal");

        Lbweight.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Lbweight.setText("Peso (em kg):");

        Lbheight.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Lbheight.setText("Altura (em cm):");

        Txweight.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        Txweight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxweightActionPerformed(evt);
            }
        });

        Txheight.setFont(new java.awt.Font("DialogInput", 2, 12)); // NOI18N
        Txheight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxheightActionPerformed(evt);
            }
        });

        Btcalc.setText("Calcular");
        Btcalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtcalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InputPanelLayout = new javax.swing.GroupLayout(InputPanel);
        InputPanel.setLayout(InputPanelLayout);
        InputPanelLayout.setHorizontalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Welcome))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lbweight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Lbheight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txweight, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(Txheight)))
                    .addGroup(InputPanelLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Btcalc)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        InputPanelLayout.setVerticalGroup(
            InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Welcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbweight)
                    .addComponent(Txweight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbheight)
                    .addComponent(Txheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btcalc)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        OutPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Lbresp.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout OutPanelLayout = new javax.swing.GroupLayout(OutPanel);
        OutPanel.setLayout(OutPanelLayout);
        OutPanelLayout.setHorizontalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(Lbresp, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OutPanelLayout.setVerticalGroup(
            OutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Lbresp)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(OutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(InputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxweightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxweightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxweightActionPerformed

    private void TxheightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxheightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxheightActionPerformed

    private void BtcalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtcalcActionPerformed
        calc();
    }//GEN-LAST:event_BtcalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIExercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIExercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIExercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIExercicio02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIExercicio02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btcalc;
    private javax.swing.JPanel InputPanel;
    private javax.swing.JLabel Lbheight;
    private javax.swing.JLabel Lbresp;
    private javax.swing.JLabel Lbweight;
    private javax.swing.JPanel OutPanel;
    private javax.swing.JTextField Txheight;
    private javax.swing.JTextField Txweight;
    private javax.swing.JLabel Welcome;
    // End of variables declaration//GEN-END:variables

    public void calc() {
        // variaveis
    Double Altura;
    Double Peso;
    Double Imc;
    String mensagem;
    
        // captura do que foi digitado
    Altura = Double.parseDouble(Txheight.getText());
    Peso = Double.parseDouble(Txweight.getText());
    
        // calculo
    Imc = Peso/(Altura/100 * Altura/100);
    
    if (Imc < 18.5) {
        mensagem = " Baixo peso(grau I)";
    }else if (Imc < 24.9) {
        mensagem = " Normal (?)";
    }else if (Imc < 29.9) {
        mensagem = " Sobrepeso";
    }else if (Imc < 34.9) {
        mensagem = " Obeso grau I";
    }else if (Imc < 39.9) {
        mensagem =  " Obeso grau II";
    }else {
        mensagem =  " Obeso grau III ou mórbido";
    }
    
    Lbresp.setText(mensagem);
}

}


